apiVersion: v1
kind: Service
metadata:
  name: jira
  labels:
    app: jira
spec:
  type: LoadBalancer
  externalIPs:
    - <node ip>
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  sessionAffinity: ClientIP
  selector:
    app: jira