apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  ports:
    - port: 2049
  selector:
    role: nfs-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: itsthenetwork/nfs-server-alpine:12
        ports:
        - containerPort: 2049
        securityContext:
          privileged: true
        env:
        - name: SHARED_DIRECTORY
          value: /exports
        args:
        - /exports
        volumeMounts:
        - name: nfs-data
          mountPath: /exports
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
      volumes:
      - name: nfs-data
        persistentVolumeClaim:
          claimName: nfs-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
