apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-shared-home-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: <nfs-server-ip>
    path: "/"
  storageClassName: "jira-shared-home"