apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-shared-home-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: jira-shared-home-pv
  storageClassName: "jira-shared-home"